default: &default
  title: pic-social
  host: localhost:3000

  # redis:
  #   host: 127.0.0.1
  #   port: 6379
  #   db: 0

development:
  <<: *default

test:
  <<: *default
  admin_emails:

production:
  <<: *default

  admin_emails:
    # - admin@example.com
